version: '3.8'

services:

  clickhouse_server:
    container_name: clickhouse_vaton
    image: yandex/clickhouse-server
    restart: always
    env_file:
      - bd.env
    #    volumes:
    #      - "./clickhouse_init.sql:/docker-entrypoint-initdb.d/init.sql"
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
  mongo:
    container_name: mongo_vaton
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - bd.env
    volumes:
        - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  db:
    image: postgres:latest
    container_name: postgres_vaton
    restart: always
    env_file:
      - bd.env
    ports:
      - '5432:5432'
    expose:
      - "5432"
    volumes:
      - ./data:/var/lib/postgresql/data