""" association_user_role check 1 

Revision ID: 12f6172409d7
Revises: 2d651a950f80
Create Date: 2022-05-10 22:18:59.044908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12f6172409d7'
down_revision = '2d651a950f80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
