"""asdasdfsdafsdsdfsdff

Revision ID: 1f16d23b4174
Revises: 7b9650a6aae6
Create Date: 2022-05-09 21:47:34.608859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f16d23b4174'
down_revision = '7b9650a6aae6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
