""" association_user_role check 

Revision ID: 2d651a950f80
Revises: 1f16d23b4174
Create Date: 2022-05-10 21:37:56.403829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d651a950f80'
down_revision = '1f16d23b4174'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
