""" add finger print

Revision ID: 6389f9ebd9fe
Revises: a7ce61b1ca2c
Create Date: 2022-05-11 01:10:05.966568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6389f9ebd9fe'
down_revision = 'a7ce61b1ca2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vaton_user_device', sa.Column('finger_print', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vaton_user_device', 'finger_print')
    # ### end Alembic commands ###
