"""asdasdfsdafsdf

Revision ID: 7b9650a6aae6
Revises: e96dda10b472
Create Date: 2022-05-09 21:29:05.917074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b9650a6aae6'
down_revision = 'e96dda10b472'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
