""" association_user_role check 2 

Revision ID: a7ce61b1ca2c
Revises: 12f6172409d7
Create Date: 2022-05-10 22:27:52.979281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7ce61b1ca2c'
down_revision = '12f6172409d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('association_user_role_vaton_user_id_fkey', 'association_user_role', type_='foreignkey')
    op.create_foreign_key(None, 'association_user_role', 'vaton_user', ['vaton_user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('vaton_user_device_id_user_fkey', 'vaton_user_device', type_='foreignkey')
    op.create_foreign_key(None, 'vaton_user_device', 'vaton_user', ['id_user'], ['id'], ondelete='CASCADE')
    op.drop_constraint('vaton_user_info_id_user_fkey', 'vaton_user_info', type_='foreignkey')
    op.create_foreign_key(None, 'vaton_user_info', 'vaton_user', ['id_user'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vaton_user_info', type_='foreignkey')
    op.create_foreign_key('vaton_user_info_id_user_fkey', 'vaton_user_info', 'vaton_user', ['id_user'], ['id'])
    op.drop_constraint(None, 'vaton_user_device', type_='foreignkey')
    op.create_foreign_key('vaton_user_device_id_user_fkey', 'vaton_user_device', 'vaton_user', ['id_user'], ['id'])
    op.drop_constraint(None, 'association_user_role', type_='foreignkey')
    op.create_foreign_key('association_user_role_vaton_user_id_fkey', 'association_user_role', 'vaton_user', ['vaton_user_id'], ['id'])
    # ### end Alembic commands ###
