""" start

Revision ID: bf75cdb81160
Revises: 
Create Date: 2022-05-02 02:23:14.598216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf75cdb81160'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vaton_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('registration_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vaton_user_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bio')
    )
    op.create_table('vaton_user_role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role')
    )
    op.create_table('association_user_role',
    sa.Column('vaton_user_id', sa.Integer(), nullable=False),
    sa.Column('vaton_user_role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vaton_user_id'], ['vaton_user.id'], ),
    sa.ForeignKeyConstraint(['vaton_user_role_id'], ['vaton_user_role.id'], ),
    sa.PrimaryKeyConstraint('vaton_user_id', 'vaton_user_role_id')
    )
    op.create_table('vaton_user_device',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['vaton_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vaton_user_device')
    op.drop_table('association_user_role')
    op.drop_table('vaton_user_role')
    op.drop_table('vaton_user_info')
    op.drop_table('vaton_user')
    # ### end Alembic commands ###
