""" add state

Revision ID: ce65aa8cb606
Revises: 6389f9ebd9fe
Create Date: 2022-05-11 15:20:24.608230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce65aa8cb606'
down_revision = '6389f9ebd9fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vaton_user_device', sa.Column('state', sa.String(), nullable=True))
    op.drop_column('vaton_user_device', 'finger_print')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vaton_user_device', sa.Column('finger_print', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('vaton_user_device', 'state')
    # ### end Alembic commands ###
