""" VUserRole del id 

Revision ID: e96dda10b472
Revises: a3df2387d145
Create Date: 2022-05-09 18:04:06.873169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e96dda10b472'
down_revision = 'a3df2387d145'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
